### ISSUE TITLE
Incorrect font size for labeled parameters

### ISSUE THREAD

**Issue by antoine1fr** [toroidal-code/language-ocaml#1]
Labeled and optional parameters don't render properly as you can see in the attached screenshot.

I'm using Atom 0.115.0.

![screen shot 2014-07-22 at 16 41 17](https://cloud.githubusercontent.com/assets/1477815/3659491/51b82710-11ae-11e4-9592-048afdbdbe75.png)

**Comment by toroidal-code** [comment]
That's... interesting. I'll look into why this is happening.

**Comment by antoine1fr** [comment]
Thanks, this issue is resolved for me.
