### ISSUE TITLE
Cursor in wrong place after labeled parameters

### ISSUE THREAD

**Issue by mikeecb** [toroidal-code/language-ocaml#2]
Cursor jumps about and is not in the correct place after labeled parameters. Fixes after you new line. 

![screen shot 2014-08-29 at 14 05 52 2](https://cloud.githubusercontent.com/assets/5933498/4090478/4e645434-2f7d-11e4-9805-cca6f305413f.png)

**Comment by toroidal-code** [comment]
I'll take a look into this. It's probably a lookhead issue in one of the regexes.

**Comment by toroidal-code** [comment]
Pull request #3 should fix some of this.

**Comment by antoine1fr** [comment]
Thanks, this is effectively not an issue anymore.
