### ISSUE TITLE
Let and in + highlight of function

### ISSUE THREAD

**Issue by VincentCheval** [toroidal-code/language-ocaml#30]
Hello,

I think there are couple of issues that were added in the last update. 
- The function names are not highlighted anymore (unless it was never intended)
- There are issues with the definition structure `` let x = z and y = t in ...``. The ``and`` is not highlighted as the ``let`` is. Moreover the second ``=`` is highlighted as if it was the comparaison operator. Moreover, with types, it's weirder:
```
type x = X | Y 

and y = A | B
```
does not color correctly the ``and`` and the second ``=`` but it works well in the following two cases: 
```
type x = X | Y  and y = A | B
```
```
type x = X | Y 
and y = A | B
```

Good luck 😊 and thanks for that very nice package !

**Comment by VincentCheval** [comment]
I'm adding another issue that I recently noticed. In the following code:

```
type ('a,'b) element

type ('a,'b) test =
  {
    x : ('a,'b) element;
    y : ('a, 'b) element
  }
```
the part ``type ('a,'b) element`` and ``type ('a,'b) test`` are fully highlighted. However, for the parts  ``x : ('a,'b) element;`` and ``y : ('a, 'b) element``, we obtained two different behaviors. For ``x : ('a,'b) element;``, the parenthesis are white,  the ``'a`` and ``element`` are highlighted as types but the ``'b`` stays white.

On the other hand, in ``y : ('a, 'b) element`` all ``'a``, ``'b`` and ``element`` are highlighted as types but the parenthesis stay white.

Thanks !

**Comment by mroch** [comment]
cc @AndreasDahl

**Comment by AndreasDahl** [comment]
I were on vacation last week. Will look at it this week.

**Comment by AndreasDahl** [comment]
Can we please split this issue into separate issues for the individual bugs. Makes it easier to organize work and track progress.

**Comment by mroch** [comment]
i think the issues in the OP are fixed now. please reopen new issues if we missed anything.
