### ISSUE TITLE
Travis Integration

### ISSUE THREAD

**Issue by AndreasDahl** [toroidal-code/language-ocaml#33]
This project already has a [travis file](https://github.com/toroidal-code/language-ocaml/blob/master/.travis.yml). You should set up a travis integration to run specs on all commits and PRs

**Comment by mroch** [comment]
@toroidal-code enabled Travis (https://travis-ci.org/toroidal-code/language-ocaml). we'll see what happens on the next commit. @AndreasDahl, want to add a badge to the readme?
