### ISSUE TITLE
How to configure nuclide-ocaml so it will not complain about Unbound module?

### ISSUE THREAD

**Issue by acierto** [toroidal-code/language-ocaml#37]
I have a very basic project which I set up by means of OASIS. I build it with command ocaml setup.ml -build

In my project I have 2 files:

 - dir.ml -> where I traverse all files in folder
 - main.ml -> where I open it to call the method from dir.ml
When I execute ocaml setup.ml -build - no errors or problems, it compiles perfectly, works without any issue.

But in Atom, I see Error: 'Unbound module Dir'. How to configure it that nuclide-ocaml will not complain on that stuff?

<img width="1245" alt="screen shot 2017-05-22 at 20 27 14" src="https://cloud.githubusercontent.com/assets/2265094/26323765/6d59c232-3f30-11e7-86fd-286d672e5eda.png">

**Comment by AndreasDahl** [comment]
It sounds like your problem is with https://github.com/facebook/nuclide and not this package. 😄

**Comment by mroch** [comment]
agreed, this comes from nuclide's merlin integration. can you report this in the nuclide repo? nice to know there are some other nuclide+ocaml users out there!
