### ISSUE TITLE
Support for local opens

### ISSUE THREAD

**Issue by antoine1fr** [toroidal-code/language-ocaml#6]
Here is the current behavior, when [opening a module locally](http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec225):

![screen shot 2015-05-19 at 16 42 39](https://cloud.githubusercontent.com/assets/1477815/7705699/194f9810-fe46-11e4-8040-1f84760bd471.png)

**Comment by toroidal-code** [comment]
This _should_ be trivial enough to add. I'll take a look into it.
